dependencies:
 - python=3.8
 - compilers
 - git
 - pytest
 - pytest-cov
 - pip:
    - requests
    - responses
    - fast-autocomplete==0.9.0
    - editdistance==0.6.1
    - c1-ml-core==0.5.45
    - numpy==1.24.4
    - faiss-cpu==1.7.2
    - c1-cp-python-core==10.0.7
    - torch
    - aiohttp
    - pre-commit
    - pylint
    - newrelic